// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';
import {agents} from '../models';
import {config} from '../models';
import {message} from '../models';
import {context} from '../models';

export function AllowPermission(arg1:string):Promise<void>;

export function CancelCard(arg1:string):Promise<boolean>;

export function CancelTurn(arg1:string):Promise<void>;

export function ChooseWorkspace():Promise<string>;

export function ConfigState():Promise<desktop.ConfigState>;

export function ConfigStatus():Promise<desktop.ConfigStatus>;

export function CurrentSession():Promise<string>;

export function DelegationCards():Promise<Array<desktop.KanbanCard>>;

export function DeleteSession(arg1:string):Promise<void>;

export function DenyPermission(arg1:string):Promise<void>;

export function ExportSession(arg1:string):Promise<string>;

export function FileDiff(arg1:string):Promise<string>;

export function GetModel():Promise<string>;

export function GetThink():Promise<string>;

export function ListAgents():Promise<Array<agents.Summary>>;

export function ListDir(arg1:string):Promise<Array<desktop.FileNode>>;

export function ListSessions():Promise<Array<desktop.SessionMeta>>;

export function MCPConfig():Promise<Array<config.MCPServer>>;

export function ModelOptions():Promise<Array<desktop.ModelOption>>;

export function ModelUsage():Promise<Array<desktop.ModelUsageStat>>;

export function NewChat():Promise<string>;

export function OpenPath(arg1:string):Promise<void>;

export function OpenWorkspace(arg1:string):Promise<void>;

export function Permissions():Promise<Array<string>>;

export function Providers():Promise<Array<desktop.ProviderView>>;

export function ReadFile(arg1:string):Promise<string>;

export function ReadLog(arg1:number):Promise<string>;

export function Reload():Promise<void>;

export function RemoveWorkspace(arg1:string):Promise<void>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function ReplyPrompt(arg1:string,arg2:desktop.ReplyRequest):Promise<boolean>;

export function ResumeSession(arg1:string):Promise<string>;

export function RetryCard(arg1:string):Promise<string>;

export function SaveInstances(arg1:desktop.InferenceRequest):Promise<void>;

export function SaveMCP(arg1:Array<config.MCPServer>):Promise<void>;

export function SessionHistory(arg1:string):Promise<Array<message.Message>>;

export function SessionMode():Promise<string>;

export function SetModel(arg1:string):Promise<void>;

export function SetSessionMode(arg1:string):Promise<void>;

export function SetThink(arg1:string):Promise<void>;

export function Skills():Promise<Array<desktop.SkillDTO>>;

export function StartTurn(arg1:string):Promise<desktop.TurnStart>;

export function Startup(arg1:context.Context):Promise<void>;

export function UnregisterAgent(arg1:string):Promise<void>;

export function Version():Promise<string>;

export function Workspace():Promise<string>;

export function Workspaces():Promise<Array<desktop.WorkspaceMeta>>;
