// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AgentDetail(arg1) {
  return window['go']['desktop']['App']['AgentDetail'](arg1);
}

export function AllowPermission(arg1) {
  return window['go']['desktop']['App']['AllowPermission'](arg1);
}

export function CancelCard(arg1) {
  return window['go']['desktop']['App']['CancelCard'](arg1);
}

export function CancelTurn(arg1) {
  return window['go']['desktop']['App']['CancelTurn'](arg1);
}

export function ChooseWorkspace() {
  return window['go']['desktop']['App']['ChooseWorkspace']();
}

export function ClearCaches() {
  return window['go']['desktop']['App']['ClearCaches']();
}

export function ConfigState() {
  return window['go']['desktop']['App']['ConfigState']();
}

export function ConfigStatus() {
  return window['go']['desktop']['App']['ConfigStatus']();
}

export function ConversationDelegationCards(arg1) {
  return window['go']['desktop']['App']['ConversationDelegationCards'](arg1);
}

export function CurrentSession() {
  return window['go']['desktop']['App']['CurrentSession']();
}

export function DelegationCards() {
  return window['go']['desktop']['App']['DelegationCards']();
}

export function DeleteSession(arg1) {
  return window['go']['desktop']['App']['DeleteSession'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['desktop']['App']['DeleteSkill'](arg1);
}

export function DenyPermission(arg1) {
  return window['go']['desktop']['App']['DenyPermission'](arg1);
}

export function Diagnostics() {
  return window['go']['desktop']['App']['Diagnostics']();
}

export function EvaluateCommandPolicy(arg1) {
  return window['go']['desktop']['App']['EvaluateCommandPolicy'](arg1);
}

export function ExportSession(arg1) {
  return window['go']['desktop']['App']['ExportSession'](arg1);
}

export function FileDiff(arg1) {
  return window['go']['desktop']['App']['FileDiff'](arg1);
}

export function GetModel() {
  return window['go']['desktop']['App']['GetModel']();
}

export function GetThink() {
  return window['go']['desktop']['App']['GetThink']();
}

export function InstallSkill(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['InstallSkill'](arg1, arg2, arg3);
}

export function ListAgents() {
  return window['go']['desktop']['App']['ListAgents']();
}

export function ListDir(arg1) {
  return window['go']['desktop']['App']['ListDir'](arg1);
}

export function ListSessions() {
  return window['go']['desktop']['App']['ListSessions']();
}

export function MCPConfig() {
  return window['go']['desktop']['App']['MCPConfig']();
}

export function MCPStatus() {
  return window['go']['desktop']['App']['MCPStatus']();
}

export function MemoryConfig() {
  return window['go']['desktop']['App']['MemoryConfig']();
}

export function ModelOptions() {
  return window['go']['desktop']['App']['ModelOptions']();
}

export function ModelUsage() {
  return window['go']['desktop']['App']['ModelUsage']();
}

export function ModelUsageSeries(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['desktop']['App']['ModelUsageSeries'](arg1, arg2, arg3, arg4, arg5);
}

export function NewChat() {
  return window['go']['desktop']['App']['NewChat']();
}

export function OpenExternal(arg1) {
  return window['go']['desktop']['App']['OpenExternal'](arg1);
}

export function OpenPath(arg1) {
  return window['go']['desktop']['App']['OpenPath'](arg1);
}

export function OpenWorkspace(arg1) {
  return window['go']['desktop']['App']['OpenWorkspace'](arg1);
}

export function Permissions() {
  return window['go']['desktop']['App']['Permissions']();
}

export function PickFolder(arg1) {
  return window['go']['desktop']['App']['PickFolder'](arg1);
}

export function PluginBundle(arg1) {
  return window['go']['desktop']['App']['PluginBundle'](arg1);
}

export function PluginInstall(arg1) {
  return window['go']['desktop']['App']['PluginInstall'](arg1);
}

export function PluginList() {
  return window['go']['desktop']['App']['PluginList']();
}

export function PluginSetEnabled(arg1, arg2) {
  return window['go']['desktop']['App']['PluginSetEnabled'](arg1, arg2);
}

export function PluginUninstall(arg1) {
  return window['go']['desktop']['App']['PluginUninstall'](arg1);
}

export function ProjectConfigStatus() {
  return window['go']['desktop']['App']['ProjectConfigStatus']();
}

export function Providers() {
  return window['go']['desktop']['App']['Providers']();
}

export function ReadFile(arg1) {
  return window['go']['desktop']['App']['ReadFile'](arg1);
}

export function ReadLog(arg1) {
  return window['go']['desktop']['App']['ReadLog'](arg1);
}

export function RedoChange() {
  return window['go']['desktop']['App']['RedoChange']();
}

export function Reload() {
  return window['go']['desktop']['App']['Reload']();
}

export function RemoveWorkspace(arg1) {
  return window['go']['desktop']['App']['RemoveWorkspace'](arg1);
}

export function RenameSession(arg1, arg2) {
  return window['go']['desktop']['App']['RenameSession'](arg1, arg2);
}

export function RenderPatch(arg1) {
  return window['go']['desktop']['App']['RenderPatch'](arg1);
}

export function RenderSkillPatch(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['RenderSkillPatch'](arg1, arg2, arg3);
}

export function ReplyPrompt(arg1, arg2) {
  return window['go']['desktop']['App']['ReplyPrompt'](arg1, arg2);
}

export function ResumeSession(arg1) {
  return window['go']['desktop']['App']['ResumeSession'](arg1);
}

export function RunSandboxProbe() {
  return window['go']['desktop']['App']['RunSandboxProbe']();
}

export function SaveInstances(arg1) {
  return window['go']['desktop']['App']['SaveInstances'](arg1);
}

export function SaveMCP(arg1) {
  return window['go']['desktop']['App']['SaveMCP'](arg1);
}

export function SaveMemory(arg1) {
  return window['go']['desktop']['App']['SaveMemory'](arg1);
}

export function SearchFiles(arg1, arg2) {
  return window['go']['desktop']['App']['SearchFiles'](arg1, arg2);
}

export function SecretDelete(arg1, arg2) {
  return window['go']['desktop']['App']['SecretDelete'](arg1, arg2);
}

export function SecretExists(arg1, arg2) {
  return window['go']['desktop']['App']['SecretExists'](arg1, arg2);
}

export function SessionHistory(arg1) {
  return window['go']['desktop']['App']['SessionHistory'](arg1);
}

export function SessionMode() {
  return window['go']['desktop']['App']['SessionMode']();
}

export function SetModel(arg1) {
  return window['go']['desktop']['App']['SetModel'](arg1);
}

export function SetProjectTrust(arg1, arg2) {
  return window['go']['desktop']['App']['SetProjectTrust'](arg1, arg2);
}

export function SetSessionMode(arg1) {
  return window['go']['desktop']['App']['SetSessionMode'](arg1);
}

export function SetThink(arg1) {
  return window['go']['desktop']['App']['SetThink'](arg1);
}

export function Skills() {
  return window['go']['desktop']['App']['Skills']();
}

export function StartTurn(arg1) {
  return window['go']['desktop']['App']['StartTurn'](arg1);
}

export function Startup(arg1) {
  return window['go']['desktop']['App']['Startup'](arg1);
}

export function TestMCP(arg1) {
  return window['go']['desktop']['App']['TestMCP'](arg1);
}

export function UndoChange() {
  return window['go']['desktop']['App']['UndoChange']();
}

export function UndoState() {
  return window['go']['desktop']['App']['UndoState']();
}

export function UnregisterAgent(arg1) {
  return window['go']['desktop']['App']['UnregisterAgent'](arg1);
}

export function UpdateAgent(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['UpdateAgent'](arg1, arg2, arg3);
}

export function Version() {
  return window['go']['desktop']['App']['Version']();
}

export function Workspace() {
  return window['go']['desktop']['App']['Workspace']();
}

export function Workspaces() {
  return window['go']['desktop']['App']['Workspaces']();
}
