// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';
import {agents} from '../models';
import {config} from '../models';
import {message} from '../models';
import {context} from '../models';
import {undo} from '../models';

export function AgentDetail(arg1:string):Promise<desktop.AgentDetail>;

export function AllowPermission(arg1:string):Promise<void>;

export function CancelCard(arg1:string):Promise<boolean>;

export function CancelTurn(arg1:string):Promise<void>;

export function ChooseWorkspace():Promise<string>;

export function ClearCaches():Promise<desktop.CacheClearResult>;

export function ConfigState():Promise<desktop.ConfigState>;

export function ConfigStatus():Promise<desktop.ConfigStatus>;

export function ConversationDelegationCards(arg1:string):Promise<Array<desktop.KanbanCard>>;

export function CurrentSession():Promise<string>;

export function DelegationCards():Promise<Array<desktop.KanbanCard>>;

export function DeleteSession(arg1:string):Promise<void>;

export function DeleteSkill(arg1:string):Promise<void>;

export function DenyPermission(arg1:string):Promise<void>;

export function Diagnostics():Promise<desktop.DiagnosticsReport>;

export function EvaluateCommandPolicy(arg1:string):Promise<desktop.PolicyDecision>;

export function ExportSession(arg1:string):Promise<string>;

export function FileDiff(arg1:string):Promise<string>;

export function GetModel():Promise<string>;

export function GetThink():Promise<string>;

export function InstallSkill(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ListAgents():Promise<Array<agents.Summary>>;

export function ListDir(arg1:string):Promise<Array<desktop.FileNode>>;

export function ListSessions():Promise<Array<desktop.SessionMeta>>;

export function MCPConfig():Promise<Array<config.MCPServer>>;

export function MCPStatus():Promise<Array<desktop.MCPStatusDTO>>;

export function MemoryConfig():Promise<config.MemorySettings>;

export function ModelOptions():Promise<Array<desktop.ModelOption>>;

export function ModelUsage():Promise<Array<desktop.ModelUsageStat>>;

export function ModelUsageSeries(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string):Promise<Array<desktop.UsagePoint>>;

export function NewChat():Promise<string>;

export function OpenExternal(arg1:string):Promise<void>;

export function OpenPath(arg1:string):Promise<void>;

export function OpenWorkspace(arg1:string):Promise<void>;

export function Permissions():Promise<Array<string>>;

export function Providers():Promise<Array<desktop.ProviderView>>;

export function ReadFile(arg1:string):Promise<string>;

export function ReadLog(arg1:number):Promise<string>;

export function RedoChange():Promise<Array<string>>;

export function Reload():Promise<void>;

export function RemoveWorkspace(arg1:string):Promise<void>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function RenderPatch(arg1:string):Promise<Array<desktop.PatchFileDTO>>;

export function RenderSkillPatch(arg1:string,arg2:string,arg3:string):Promise<Array<desktop.PatchFileDTO>>;

export function ReplyPrompt(arg1:string,arg2:desktop.ReplyRequest):Promise<boolean>;

export function ResumeSession(arg1:string):Promise<string>;

export function RunSandboxProbe():Promise<desktop.SandboxProbeResult>;

export function SaveInstances(arg1:desktop.InferenceRequest):Promise<void>;

export function SaveMCP(arg1:Array<config.MCPServer>):Promise<void>;

export function SaveMemory(arg1:config.MemorySettings):Promise<void>;

export function SearchFiles(arg1:string,arg2:number):Promise<Array<desktop.SearchFileHit>>;

export function SessionHistory(arg1:string):Promise<Array<message.Message>>;

export function SessionMode():Promise<string>;

export function SetModel(arg1:string):Promise<void>;

export function SetSessionMode(arg1:string):Promise<void>;

export function SetThink(arg1:string):Promise<void>;

export function Skills():Promise<Array<desktop.SkillDTO>>;

export function StartTurn(arg1:string):Promise<desktop.TurnStart>;

export function Startup(arg1:context.Context):Promise<void>;

export function TestMCP(arg1:config.MCPServer):Promise<void>;

export function UndoChange():Promise<Array<string>>;

export function UndoState():Promise<undo.State>;

export function UnregisterAgent(arg1:string):Promise<void>;

export function UpdateAgent(arg1:string,arg2:string,arg3:string):Promise<desktop.AgentUpdateResult>;

export function Version():Promise<string>;

export function Workspace():Promise<string>;

export function Workspaces():Promise<Array<desktop.WorkspaceMeta>>;
