// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';
import {agents} from '../models';

export function CancelTurn(arg1:string):Promise<void>;

export function ConfigState():Promise<desktop.ConfigState>;

export function ConfigStatus():Promise<desktop.ConfigStatus>;

export function ListAgents():Promise<Array<agents.Summary>>;

export function ListDir(arg1:string):Promise<Array<desktop.FileNode>>;

export function NewChat():Promise<string>;

export function OpenPath(arg1:string):Promise<void>;

export function Providers():Promise<Array<desktop.ProviderView>>;

export function Reload():Promise<void>;

export function ReplyPrompt(arg1:string,arg2:desktop.ReplyRequest):Promise<boolean>;

export function SaveSetup(arg1:desktop.SetupRequest):Promise<void>;

export function SessionMode():Promise<string>;

export function SetSessionMode(arg1:string):Promise<void>;

export function StartTurn(arg1:string):Promise<desktop.TurnStart>;

export function UnregisterAgent(arg1:string):Promise<void>;

export function Version():Promise<string>;

export function Workspace():Promise<string>;
