// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTurn(arg1) {
  return window['go']['desktop']['App']['CancelTurn'](arg1);
}

export function ConfigState() {
  return window['go']['desktop']['App']['ConfigState']();
}

export function ConfigStatus() {
  return window['go']['desktop']['App']['ConfigStatus']();
}

export function CurrentSession() {
  return window['go']['desktop']['App']['CurrentSession']();
}

export function DelegationCards() {
  return window['go']['desktop']['App']['DelegationCards']();
}

export function FileDiff(arg1) {
  return window['go']['desktop']['App']['FileDiff'](arg1);
}

export function ListAgents() {
  return window['go']['desktop']['App']['ListAgents']();
}

export function ListDir(arg1) {
  return window['go']['desktop']['App']['ListDir'](arg1);
}

export function ListSessions() {
  return window['go']['desktop']['App']['ListSessions']();
}

export function NewChat() {
  return window['go']['desktop']['App']['NewChat']();
}

export function OpenPath(arg1) {
  return window['go']['desktop']['App']['OpenPath'](arg1);
}

export function Providers() {
  return window['go']['desktop']['App']['Providers']();
}

export function ReadFile(arg1) {
  return window['go']['desktop']['App']['ReadFile'](arg1);
}

export function Reload() {
  return window['go']['desktop']['App']['Reload']();
}

export function ReplyPrompt(arg1, arg2) {
  return window['go']['desktop']['App']['ReplyPrompt'](arg1, arg2);
}

export function ResumeSession(arg1) {
  return window['go']['desktop']['App']['ResumeSession'](arg1);
}

export function SaveSetup(arg1) {
  return window['go']['desktop']['App']['SaveSetup'](arg1);
}

export function SessionHistory(arg1) {
  return window['go']['desktop']['App']['SessionHistory'](arg1);
}

export function SessionMode() {
  return window['go']['desktop']['App']['SessionMode']();
}

export function SetSessionMode(arg1) {
  return window['go']['desktop']['App']['SetSessionMode'](arg1);
}

export function StartTurn(arg1) {
  return window['go']['desktop']['App']['StartTurn'](arg1);
}

export function UnregisterAgent(arg1) {
  return window['go']['desktop']['App']['UnregisterAgent'](arg1);
}

export function Version() {
  return window['go']['desktop']['App']['Version']();
}

export function Workspace() {
  return window['go']['desktop']['App']['Workspace']();
}
