// Package config owns opencraft's embedded deploy assets: the internal
// base opencraft.yaml document, the graph definition, and prompt
// templates. The user configuration layer (~/.opencraft/config/
// opencraft.yaml) is generated by the settings page, not
// embedded here.
package config

import "embed"

// Default deploy assets. The base document is split across embedded
// layer files — opencraft.yaml (core resources), tools.yaml,
// agents.yaml, runtime.yaml, and inference.yaml — each registered as
// its own layer by Manager.Load. The user configuration layer
// (~/.opencraft/config/opencraft.yaml) stays a single editable
// document generated by the settings page wizard. The graph definition
// and its node scripts/prompt are embedded too — they are only read
// from disk when a config layer overrides the graph reference with a
// {file: ...} source.
//
//go:embed assets
var assets embed.FS

// FS returns the embedded deploy asset filesystem (for embed sources
// referenced from opencraft.yaml, e.g. the graph definition).
func FS() embed.FS { return assets }

// EmbeddedOpenCraft returns the internal deploy document.
func EmbeddedOpenCraft() ([]byte, error) {
	return assets.ReadFile("assets/opencraft.yaml")
}
