package worldstate

import (
	"bytes"
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/GizClaw/flowcraft/core/agent"
	corememory "github.com/GizClaw/flowcraft/core/memory"
	"github.com/GizClaw/flowcraft/core/message"
)

// The world node is the one graph script that prepends model-visible
// context (instructions, environment, permissions, memory) to every
// turn. Go writes the payload into board vars and the node replays it
// onto the MainChannel, so two things have to agree and nothing else
// checks them:
//
//   - the board var names on both sides, and
//   - the JSON shape of a section (id/role/content).
//
// A mismatch is silent and severe: the model loses its instructions or
// the count markers degrade, and the memory hooks that locate the user
// turn on the channel start slicing in the wrong place. The fixture
// below carries what Go actually writes, and
// frontend/src/lib/worldNodeMirror.test.ts runs world.js against it.

type worldNodeCase struct {
	Name string `json:"name"`
	// Sections is the string Go writes to world.sections.
	Sections string `json:"sections"`
	// History is the string Go writes to world.history; empty when the
	// turn does not replay history, in which case the var is unset.
	History string `json:"history,omitempty"`
	// Existing is the channel the node finds on the board when it runs.
	Existing []json.RawMessage `json:"existing"`
}

type worldNodeFixture struct {
	Note  string          `json:"note"`
	Cases []worldNodeCase `json:"cases"`
}

// worldNodeFixtureCases renders real world state for the cases the
// node has to survive: an ordinary turn, and a full-history replay turn
// where world.history is set as well.
func worldNodeFixtureCases(t *testing.T, workBase string) []worldNodeCase {
	t.Helper()
	existing := []message.Message{
		message.NewTextMessage(message.RoleUser, "the user's current turn"),
	}
	build := func(name string, svc *Service) worldNodeCase {
		t.Helper()
		board := agent.NewBoard()
		if err := svc.RenderToBoard(
			context.Background(), "assistant", "s-c1", "hi", nil, board,
		); err != nil {
			t.Fatalf("%s: render: %v", name, err)
		}
		entry := worldNodeCase{
			Name:     name,
			Sections: normalizePath(board.GetVarString("world.sections"), workBase),
			History:  normalizePath(board.GetVarString("world.history"), workBase),
		}
		for _, m := range existing {
			raw, err := json.Marshal(m)
			if err != nil {
				t.Fatalf("%s: marshal existing: %v", name, err)
			}
			entry.Existing = append(entry.Existing, raw)
		}
		return entry
	}
	plain := New(Options{
		WorkBase:          workBase,
		CollaborationMode: "workspace",
	})
	replay := New(Options{
		WorkBase:          workBase,
		CollaborationMode: "workspace",
	})
	replay.memory = replayMemory{stubMemory{items: []corememory.ContextItem{
		{
			Kind:        corememory.ContextRawMessage,
			MessageRole: message.RoleUser,
			Content: message.Content{Parts: []message.Part{
				message.TextPart{Text: "replayed user turn"},
			}},
		},
		{
			Kind:        corememory.ContextRawMessage,
			MessageRole: message.RoleAssistant,
			Content: message.Content{Parts: []message.Part{
				message.TextPart{Text: "replayed assistant turn"},
			}},
		},
	}}}
	return []worldNodeCase{
		build("plain turn", plain),
		build("full-history replay", replay),
	}
}

// normalizePath keeps the fixture stable across runs: the environment
// section embeds the workspace root, which lives in a temp dir.
func normalizePath(s, workBase string) string {
	if workBase == "" {
		return s
	}
	return strings.ReplaceAll(s, workBase, "<workbase>")
}

// TestWorldNodeFixtureMatchesRenderedState pins the fixture to what Go
// writes. Run with UPDATE_GOLDEN=1 after an intentional change, then run
// the frontend test that reads the same file.
func TestWorldNodeFixtureMatchesRenderedState(t *testing.T) {
	workBase := filepath.Join(t.TempDir(), "ws")
	if err := os.MkdirAll(workBase, 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(
		filepath.Join(workBase, "AGENTS.md"),
		[]byte("project rules for the fixture"), 0o600,
	); err != nil {
		t.Fatal(err)
	}
	fixture := worldNodeFixture{
		Note: "Generated by TestWorldNodeFixtureMatchesRenderedState " +
			"(UPDATE_GOLDEN=1). The graph's world node is checked against " +
			"this file by frontend/src/lib/worldNodeMirror.test.ts.",
		Cases: worldNodeFixtureCases(t, workBase),
	}
	got, err := json.MarshalIndent(fixture, "", "  ")
	if err != nil {
		t.Fatalf("marshal fixture: %v", err)
	}
	got = append(got, '\n')

	path := filepath.Join("testdata", "world_cases.json")
	if os.Getenv("UPDATE_GOLDEN") == "1" {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, got, 0o644); err != nil {
			t.Fatal(err)
		}
		t.Logf("wrote %s (%d bytes)", path, len(got))
		return
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("fixture is stale; rerun with UPDATE_GOLDEN=1:\n--- want\n%s\n--- got\n%s",
			want, got)
	}
}
