// execd is the wire protocol between the OpenCraft host process and its
// self-forked exec supervisor child. The child is always the same
// binary as the parent, and the Hello handshake compares the protocol
// version before anything else, so the schema can be rewritten
// wholesale (no backward compatibility is kept).
//
// Frames are written as a 4-byte big-endian length followed by the
// serialized Frame.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: internal/capabilities/execd/execd.proto

package execd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Frame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Request/response correlation. Zero on notifications.
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Request only: relative budget in milliseconds. Zero means no
	// deadline beyond the connection lifetime.
	DeadlineMs int64 `protobuf:"varint,2,opt,name=deadline_ms,json=deadlineMs,proto3" json:"deadline_ms,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*Frame_Request
	//	*Frame_Response
	//	*Frame_Notification
	Body          isFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_internal_capabilities_execd_execd_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Frame) GetDeadlineMs() int64 {
	if x != nil {
		return x.DeadlineMs
	}
	return 0
}

func (x *Frame) GetBody() isFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Frame) GetRequest() *Request {
	if x != nil {
		if x, ok := x.Body.(*Frame_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *Frame) GetResponse() *Response {
	if x != nil {
		if x, ok := x.Body.(*Frame_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *Frame) GetNotification() *Notification {
	if x != nil {
		if x, ok := x.Body.(*Frame_Notification); ok {
			return x.Notification
		}
	}
	return nil
}

type isFrame_Body interface {
	isFrame_Body()
}

type Frame_Request struct {
	Request *Request `protobuf:"bytes,3,opt,name=request,proto3,oneof"`
}

type Frame_Response struct {
	Response *Response `protobuf:"bytes,4,opt,name=response,proto3,oneof"`
}

type Frame_Notification struct {
	Notification *Notification `protobuf:"bytes,5,opt,name=notification,proto3,oneof"`
}

func (*Frame_Request) isFrame_Body() {}

func (*Frame_Response) isFrame_Body() {}

func (*Frame_Notification) isFrame_Body() {}

type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Method:
	//
	//	*Request_Hello
	//	*Request_Bind
	//	*Request_Unbind
	//	*Request_Start
	//	*Request_Read
	//	*Request_Write
	//	*Request_CloseInput
	//	*Request_Signal
	//	*Request_Resize
	//	*Request_Terminate
	//	*Request_Release
	//	*Request_Wait
	//	*Request_Ping
	//	*Request_Diagnostics
	Method        isRequest_Method `protobuf_oneof:"method"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_internal_capabilities_execd_execd_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetMethod() isRequest_Method {
	if x != nil {
		return x.Method
	}
	return nil
}

func (x *Request) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Method.(*Request_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *Request) GetBind() *Bind {
	if x != nil {
		if x, ok := x.Method.(*Request_Bind); ok {
			return x.Bind
		}
	}
	return nil
}

func (x *Request) GetUnbind() *Unbind {
	if x != nil {
		if x, ok := x.Method.(*Request_Unbind); ok {
			return x.Unbind
		}
	}
	return nil
}

func (x *Request) GetStart() *Start {
	if x != nil {
		if x, ok := x.Method.(*Request_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *Request) GetRead() *Read {
	if x != nil {
		if x, ok := x.Method.(*Request_Read); ok {
			return x.Read
		}
	}
	return nil
}

func (x *Request) GetWrite() *Write {
	if x != nil {
		if x, ok := x.Method.(*Request_Write); ok {
			return x.Write
		}
	}
	return nil
}

func (x *Request) GetCloseInput() *CloseInput {
	if x != nil {
		if x, ok := x.Method.(*Request_CloseInput); ok {
			return x.CloseInput
		}
	}
	return nil
}

func (x *Request) GetSignal() *Signal {
	if x != nil {
		if x, ok := x.Method.(*Request_Signal); ok {
			return x.Signal
		}
	}
	return nil
}

func (x *Request) GetResize() *Resize {
	if x != nil {
		if x, ok := x.Method.(*Request_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

func (x *Request) GetTerminate() *Terminate {
	if x != nil {
		if x, ok := x.Method.(*Request_Terminate); ok {
			return x.Terminate
		}
	}
	return nil
}

func (x *Request) GetRelease() *Release {
	if x != nil {
		if x, ok := x.Method.(*Request_Release); ok {
			return x.Release
		}
	}
	return nil
}

func (x *Request) GetWait() *Wait {
	if x != nil {
		if x, ok := x.Method.(*Request_Wait); ok {
			return x.Wait
		}
	}
	return nil
}

func (x *Request) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Method.(*Request_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Request) GetDiagnostics() *Diagnostics {
	if x != nil {
		if x, ok := x.Method.(*Request_Diagnostics); ok {
			return x.Diagnostics
		}
	}
	return nil
}

type isRequest_Method interface {
	isRequest_Method()
}

type Request_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type Request_Bind struct {
	Bind *Bind `protobuf:"bytes,2,opt,name=bind,proto3,oneof"`
}

type Request_Unbind struct {
	Unbind *Unbind `protobuf:"bytes,3,opt,name=unbind,proto3,oneof"`
}

type Request_Start struct {
	Start *Start `protobuf:"bytes,4,opt,name=start,proto3,oneof"`
}

type Request_Read struct {
	Read *Read `protobuf:"bytes,5,opt,name=read,proto3,oneof"`
}

type Request_Write struct {
	Write *Write `protobuf:"bytes,6,opt,name=write,proto3,oneof"`
}

type Request_CloseInput struct {
	CloseInput *CloseInput `protobuf:"bytes,7,opt,name=close_input,json=closeInput,proto3,oneof"`
}

type Request_Signal struct {
	Signal *Signal `protobuf:"bytes,8,opt,name=signal,proto3,oneof"`
}

type Request_Resize struct {
	Resize *Resize `protobuf:"bytes,9,opt,name=resize,proto3,oneof"`
}

type Request_Terminate struct {
	Terminate *Terminate `protobuf:"bytes,10,opt,name=terminate,proto3,oneof"`
}

type Request_Release struct {
	Release *Release `protobuf:"bytes,11,opt,name=release,proto3,oneof"`
}

type Request_Wait struct {
	Wait *Wait `protobuf:"bytes,12,opt,name=wait,proto3,oneof"`
}

type Request_Ping struct {
	Ping *Ping `protobuf:"bytes,13,opt,name=ping,proto3,oneof"`
}

type Request_Diagnostics struct {
	Diagnostics *Diagnostics `protobuf:"bytes,14,opt,name=diagnostics,proto3,oneof"`
}

func (*Request_Hello) isRequest_Method() {}

func (*Request_Bind) isRequest_Method() {}

func (*Request_Unbind) isRequest_Method() {}

func (*Request_Start) isRequest_Method() {}

func (*Request_Read) isRequest_Method() {}

func (*Request_Write) isRequest_Method() {}

func (*Request_CloseInput) isRequest_Method() {}

func (*Request_Signal) isRequest_Method() {}

func (*Request_Resize) isRequest_Method() {}

func (*Request_Terminate) isRequest_Method() {}

func (*Request_Release) isRequest_Method() {}

func (*Request_Wait) isRequest_Method() {}

func (*Request_Ping) isRequest_Method() {}

func (*Request_Diagnostics) isRequest_Method() {}

type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*Response_Error
	//	*Response_HelloOk
	//	*Response_BindOk
	//	*Response_Ack
	//	*Response_StartOk
	//	*Response_ReadOk
	//	*Response_TerminateOk
	//	*Response_ReleaseOk
	//	*Response_WaitOk
	//	*Response_PingOk
	//	*Response_DiagnosticsOk
	Body          isResponse_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_internal_capabilities_execd_execd_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetBody() isResponse_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Response) GetError() *Error {
	if x != nil {
		if x, ok := x.Body.(*Response_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Response) GetHelloOk() *HelloOk {
	if x != nil {
		if x, ok := x.Body.(*Response_HelloOk); ok {
			return x.HelloOk
		}
	}
	return nil
}

func (x *Response) GetBindOk() *BindOk {
	if x != nil {
		if x, ok := x.Body.(*Response_BindOk); ok {
			return x.BindOk
		}
	}
	return nil
}

func (x *Response) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Body.(*Response_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *Response) GetStartOk() *StartOk {
	if x != nil {
		if x, ok := x.Body.(*Response_StartOk); ok {
			return x.StartOk
		}
	}
	return nil
}

func (x *Response) GetReadOk() *ReadOk {
	if x != nil {
		if x, ok := x.Body.(*Response_ReadOk); ok {
			return x.ReadOk
		}
	}
	return nil
}

func (x *Response) GetTerminateOk() *TerminateOk {
	if x != nil {
		if x, ok := x.Body.(*Response_TerminateOk); ok {
			return x.TerminateOk
		}
	}
	return nil
}

func (x *Response) GetReleaseOk() *ReleaseOk {
	if x != nil {
		if x, ok := x.Body.(*Response_ReleaseOk); ok {
			return x.ReleaseOk
		}
	}
	return nil
}

func (x *Response) GetWaitOk() *WaitOk {
	if x != nil {
		if x, ok := x.Body.(*Response_WaitOk); ok {
			return x.WaitOk
		}
	}
	return nil
}

func (x *Response) GetPingOk() *PingOk {
	if x != nil {
		if x, ok := x.Body.(*Response_PingOk); ok {
			return x.PingOk
		}
	}
	return nil
}

func (x *Response) GetDiagnosticsOk() *DiagnosticsOk {
	if x != nil {
		if x, ok := x.Body.(*Response_DiagnosticsOk); ok {
			return x.DiagnosticsOk
		}
	}
	return nil
}

type isResponse_Body interface {
	isResponse_Body()
}

type Response_Error struct {
	Error *Error `protobuf:"bytes,1,opt,name=error,proto3,oneof"`
}

type Response_HelloOk struct {
	HelloOk *HelloOk `protobuf:"bytes,2,opt,name=hello_ok,json=helloOk,proto3,oneof"`
}

type Response_BindOk struct {
	BindOk *BindOk `protobuf:"bytes,3,opt,name=bind_ok,json=bindOk,proto3,oneof"`
}

type Response_Ack struct {
	Ack *Ack `protobuf:"bytes,4,opt,name=ack,proto3,oneof"`
}

type Response_StartOk struct {
	StartOk *StartOk `protobuf:"bytes,5,opt,name=start_ok,json=startOk,proto3,oneof"`
}

type Response_ReadOk struct {
	ReadOk *ReadOk `protobuf:"bytes,6,opt,name=read_ok,json=readOk,proto3,oneof"`
}

type Response_TerminateOk struct {
	TerminateOk *TerminateOk `protobuf:"bytes,7,opt,name=terminate_ok,json=terminateOk,proto3,oneof"`
}

type Response_ReleaseOk struct {
	ReleaseOk *ReleaseOk `protobuf:"bytes,8,opt,name=release_ok,json=releaseOk,proto3,oneof"`
}

type Response_WaitOk struct {
	WaitOk *WaitOk `protobuf:"bytes,9,opt,name=wait_ok,json=waitOk,proto3,oneof"`
}

type Response_PingOk struct {
	PingOk *PingOk `protobuf:"bytes,10,opt,name=ping_ok,json=pingOk,proto3,oneof"`
}

type Response_DiagnosticsOk struct {
	DiagnosticsOk *DiagnosticsOk `protobuf:"bytes,11,opt,name=diagnostics_ok,json=diagnosticsOk,proto3,oneof"`
}

func (*Response_Error) isResponse_Body() {}

func (*Response_HelloOk) isResponse_Body() {}

func (*Response_BindOk) isResponse_Body() {}

func (*Response_Ack) isResponse_Body() {}

func (*Response_StartOk) isResponse_Body() {}

func (*Response_ReadOk) isResponse_Body() {}

func (*Response_TerminateOk) isResponse_Body() {}

func (*Response_ReleaseOk) isResponse_Body() {}

func (*Response_WaitOk) isResponse_Body() {}

func (*Response_PingOk) isResponse_Body() {}

func (*Response_DiagnosticsOk) isResponse_Body() {}

type Notification struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*Notification_Cancel
	//	*Notification_Output
	//	*Notification_Exited
	//	*Notification_Closed
	//	*Notification_Lag
	Body          isNotification_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_internal_capabilities_execd_execd_proto_rawDescGZIP(), []int{3}
}

func (x *Notification) GetBody() isNotification_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Notification) GetCancel() *Cancel {
	if x != nil {
		if x, ok := x.Body.(*Notification_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *Notification) GetOutput() *Output {
	if x != nil {
		if x, ok := x.Body.(*Notification_Output); ok {
			return x.Output
		}
	}
	return nil
}

func (x *Notification) GetExited() *Exited {
	if x != nil {
		if x, ok := x.Body.(*Notification_Exited); ok {
			return x.Exited
		}
	}
	return nil
}

func (x *Notification) GetClosed() *Closed {
	if x != nil {
		if x, ok := x.Body.(*Notification_Closed); ok {
			return x.Closed
		}
	}
	return nil
}

func (x *Notification) GetLag() *Lag {
	if x != nil {
		if x, ok := x.Body.(*Notification_Lag); ok {
			return x.Lag
		}
	}
	return nil
}

type isNotification_Body interface {
	isNotification_Body()
}

type Notification_Cancel struct {
	Cancel *Cancel `protobuf:"bytes,1,opt,name=cancel,proto3,oneof"`
}

type Notification_Output struct {
	Output *Output `protobuf:"bytes,2,opt,name=output,proto3,oneof"`
}

type Notification_Exited struct {
	Exited *Exited `protobuf:"bytes,3,opt,name=exited,proto3,oneof"`
}

type Notification_Closed struct {
	Closed *Closed `protobuf:"bytes,4,opt,name=closed,proto3,oneof"`
}

type Notification_Lag struct {
	Lag *Lag `protobuf:"bytes,5,opt,name=lag,proto3,oneof"`
}

func (*Notification_Cancel) isNotification_Body() {}

func (*Notification_Output) isNotification_Body() {}

func (*Notification_Exited) isNotification_Body() {}

func (*Notification_Closed) isNotification_Body() {}

func (*Notification_Lag) isNotification_Body() {}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_internal_capabilities_execd_execd_proto_rawDescGZIP(), []int{4}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Hello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Build           string                 `protobuf:"bytes,2,opt,name=build,proto3" json:"build,omitempty"`
	Client          string                 `protobuf:"bytes,3,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_internal_capabilities_execd_execd_proto_rawDescGZIP(), []int{5}
}

func (x *Hello) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Hello) GetBuild() string {
	if x != nil {
		return x.Build
	}
	return ""
}

func (x *Hello) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

type HelloOk struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Build           string                 `protobuf:"bytes,2,opt,name=build,proto3" json:"build,omitempty"`
	Capabilities    []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	SessionId       string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HelloOk) Reset() {
	*x = HelloOk{}
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloOk) ProtoMessage() {}

func (x *HelloOk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloOk.ProtoReflect.Descriptor instead.
func (*HelloOk) Descriptor() ([]byte, []int) {
	return file_internal_capabilities_execd_execd_proto_rawDescGZIP(), []int{6}
}

func (x *HelloOk) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *HelloOk) GetBuild() string {
	if x != nil {
		return x.Build
	}
	return ""
}

func (x *HelloOk) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *HelloOk) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// SandboxPolicy mirrors opencraft's per-workspace sandbox policy.
// env_allow_set distinguishes "no allow list" (inherit) from an empty
// allow list (empty environment).
type SandboxPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WritablePaths []string               `protobuf:"bytes,1,rep,name=writable_paths,json=writablePaths,proto3" json:"writable_paths,omitempty"`
	EnvAllow      []string               `protobuf:"bytes,2,rep,name=env_allow,json=envAllow,proto3" json:"env_allow,omitempty"`
	EnvInject     map[string]string      `protobuf:"bytes,3,rep,name=env_inject,json=envInject,proto3" json:"env_inject,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EnvAllowSet   bool                   `protobuf:"varint,4,opt,name=env_allow_set,json=envAllowSet,proto3" json:"env_allow_set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxPolicy) Reset() {
	*x = SandboxPolicy{}
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxPolicy) ProtoMessage() {}

func (x *SandboxPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxPolicy.ProtoReflect.Descriptor instead.
func (*SandboxPolicy) Descriptor() ([]byte, []int) {
	return file_internal_capabilities_execd_execd_proto_rawDescGZIP(), []int{7}
}

func (x *SandboxPolicy) GetWritablePaths() []string {
	if x != nil {
		return x.WritablePaths
	}
	return nil
}

func (x *SandboxPolicy) GetEnvAllow() []string {
	if x != nil {
		return x.EnvAllow
	}
	return nil
}

func (x *SandboxPolicy) GetEnvInject() map[string]string {
	if x != nil {
		return x.EnvInject
	}
	return nil
}

func (x *SandboxPolicy) GetEnvAllowSet() bool {
	if x != nil {
		return x.EnvAllowSet
	}
	return false
}

type Bind struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workdir       string                 `protobuf:"bytes,1,opt,name=workdir,proto3" json:"workdir,omitempty"`
	Policy        *SandboxPolicy         `protobuf:"bytes,2,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bind) Reset() {
	*x = Bind{}
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bind) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bind) ProtoMessage() {}

func (x *Bind) ProtoReflect() protoreflect.Message {
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bind.ProtoReflect.Descriptor instead.
func (*Bind) Descriptor() ([]byte, []int) {
	return file_internal_capabilities_execd_execd_proto_rawDescGZIP(), []int{8}
}

func (x *Bind) GetWorkdir() string {
	if x != nil {
		return x.Workdir
	}
	return ""
}

func (x *Bind) GetPolicy() *SandboxPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type BindOk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindOk) Reset() {
	*x = BindOk{}
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindOk) ProtoMessage() {}

func (x *BindOk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindOk.ProtoReflect.Descriptor instead.
func (*BindOk) Descriptor() ([]byte, []int) {
	return file_internal_capabilities_execd_execd_proto_rawDescGZIP(), []int{9}
}

type Unbind struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unbind) Reset() {
	*x = Unbind{}
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unbind) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unbind) ProtoMessage() {}

func (x *Unbind) ProtoReflect() protoreflect.Message {
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unbind.ProtoReflect.Descriptor instead.
func (*Unbind) Descriptor() ([]byte, []int) {
	return file_internal_capabilities_execd_execd_proto_rawDescGZIP(), []int{10}
}

// ExecOptions mirrors sandbox.ExecOptions. net_policy_json carries the
// flowcraft net policy as JSON: it is a large, rarely changing struct
// owned by core, and duplicating it in protobuf would couple this
// schema to every core release.
type ExecOptions struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	WorkDir     string                 `protobuf:"bytes,1,opt,name=work_dir,json=workDir,proto3" json:"work_dir,omitempty"`
	Stdin       []byte                 `protobuf:"bytes,2,opt,name=stdin,proto3" json:"stdin,omitempty"`
	TimeoutMs   int64                  `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	EnvAllow    []string               `protobuf:"bytes,4,rep,name=env_allow,json=envAllow,proto3" json:"env_allow,omitempty"`
	EnvInject   map[string]string      `protobuf:"bytes,5,rep,name=env_inject,json=envInject,proto3" json:"env_inject,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EnvAllowSet bool                   `protobuf:"varint,6,opt,name=env_allow_set,json=envAllowSet,proto3" json:"env_allow_set,omitempty"`
	// WritePolicy: 0 = workspace (default), 1 = read-only.
	Write          uint32 `protobuf:"varint,7,opt,name=write,proto3" json:"write,omitempty"`
	MemoryBytes    int64  `protobuf:"varint,8,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	CpuMillicores  int64  `protobuf:"varint,9,opt,name=cpu_millicores,json=cpuMillicores,proto3" json:"cpu_millicores,omitempty"`
	DiskBytes      int64  `protobuf:"varint,10,opt,name=disk_bytes,json=diskBytes,proto3" json:"disk_bytes,omitempty"`
	MaxOutputBytes int64  `protobuf:"varint,11,opt,name=max_output_bytes,json=maxOutputBytes,proto3" json:"max_output_bytes,omitempty"`
	NetPolicyJson  []byte `protobuf:"bytes,12,opt,name=net_policy_json,json=netPolicyJson,proto3" json:"net_policy_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecOptions) Reset() {
	*x = ExecOptions{}
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecOptions) ProtoMessage() {}

func (x *ExecOptions) ProtoReflect() protoreflect.Message {
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecOptions.ProtoReflect.Descriptor instead.
func (*ExecOptions) Descriptor() ([]byte, []int) {
	return file_internal_capabilities_execd_execd_proto_rawDescGZIP(), []int{11}
}

func (x *ExecOptions) GetWorkDir() string {
	if x != nil {
		return x.WorkDir
	}
	return ""
}

func (x *ExecOptions) GetStdin() []byte {
	if x != nil {
		return x.Stdin
	}
	return nil
}

func (x *ExecOptions) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *ExecOptions) GetEnvAllow() []string {
	if x != nil {
		return x.EnvAllow
	}
	return nil
}

func (x *ExecOptions) GetEnvInject() map[string]string {
	if x != nil {
		return x.EnvInject
	}
	return nil
}

func (x *ExecOptions) GetEnvAllowSet() bool {
	if x != nil {
		return x.EnvAllowSet
	}
	return false
}

func (x *ExecOptions) GetWrite() uint32 {
	if x != nil {
		return x.Write
	}
	return 0
}

func (x *ExecOptions) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ExecOptions) GetCpuMillicores() int64 {
	if x != nil {
		return x.CpuMillicores
	}
	return 0
}

func (x *ExecOptions) GetDiskBytes() int64 {
	if x != nil {
		return x.DiskBytes
	}
	return 0
}

func (x *ExecOptions) GetMaxOutputBytes() int64 {
	if x != nil {
		return x.MaxOutputBytes
	}
	return 0
}

func (x *ExecOptions) GetNetPolicyJson() []byte {
	if x != nil {
		return x.NetPolicyJson
	}
	return nil
}

type Start struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessId     string                 `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	Argv          []string               `protobuf:"bytes,2,rep,name=argv,proto3" json:"argv,omitempty"`
	Cwd           string                 `protobuf:"bytes,3,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Env           map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tty           bool                   `protobuf:"varint,5,opt,name=tty,proto3" json:"tty,omitempty"`
	Rows          int32                  `protobuf:"varint,6,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          int32                  `protobuf:"varint,7,opt,name=cols,proto3" json:"cols,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,8,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	Unconfined    bool                   `protobuf:"varint,9,opt,name=unconfined,proto3" json:"unconfined,omitempty"`
	Sandbox       *ExecOptions           `protobuf:"bytes,10,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Start) Reset() {
	*x = Start{}
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Start) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Start) ProtoMessage() {}

func (x *Start) ProtoReflect() protoreflect.Message {
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Start.ProtoReflect.Descriptor instead.
func (*Start) Descriptor() ([]byte, []int) {
	return file_internal_capabilities_execd_execd_proto_rawDescGZIP(), []int{12}
}

func (x *Start) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *Start) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *Start) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *Start) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *Start) GetTty() bool {
	if x != nil {
		return x.Tty
	}
	return false
}

func (x *Start) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *Start) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *Start) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *Start) GetUnconfined() bool {
	if x != nil {
		return x.Unconfined
	}
	return false
}

func (x *Start) GetSandbox() *ExecOptions {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

type StartOk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartOk) Reset() {
	*x = StartOk{}
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOk) ProtoMessage() {}

func (x *StartOk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOk.ProtoReflect.Descriptor instead.
func (*StartOk) Descriptor() ([]byte, []int) {
	return file_internal_capabilities_execd_execd_proto_rawDescGZIP(), []int{13}
}

func (x *StartOk) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type Read struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessId     string                 `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	AfterSeq      int64                  `protobuf:"varint,2,opt,name=after_seq,json=afterSeq,proto3" json:"after_seq,omitempty"`
	MaxBytes      int32                  `protobuf:"varint,3,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	WaitMs        int64                  `protobuf:"varint,4,opt,name=wait_ms,json=waitMs,proto3" json:"wait_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Read) Reset() {
	*x = Read{}
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Read) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Read) ProtoMessage() {}

func (x *Read) ProtoReflect() protoreflect.Message {
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Read.ProtoReflect.Descriptor instead.
func (*Read) Descriptor() ([]byte, []int) {
	return file_internal_capabilities_execd_execd_proto_rawDescGZIP(), []int{14}
}

func (x *Read) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *Read) GetAfterSeq() int64 {
	if x != nil {
		return x.AfterSeq
	}
	return 0
}

func (x *Read) GetMaxBytes() int32 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

func (x *Read) GetWaitMs() int64 {
	if x != nil {
		return x.WaitMs
	}
	return 0
}

type Chunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Seq   int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	// sandbox.SessionStream: 0 stdout, 1 stderr, 2 tty.
	Stream        uint32 `protobuf:"varint,2,opt,name=stream,proto3" json:"stream,omitempty"`
	Data          []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_internal_capabilities_execd_execd_proto_rawDescGZIP(), []int{15}
}

func (x *Chunk) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Chunk) GetStream() uint32 {
	if x != nil {
		return x.Stream
	}
	return 0
}

func (x *Chunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ReadOk struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Chunks   []*Chunk               `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	NextSeq  int64                  `protobuf:"varint,2,opt,name=next_seq,json=nextSeq,proto3" json:"next_seq,omitempty"`
	Eof      bool                   `protobuf:"varint,3,opt,name=eof,proto3" json:"eof,omitempty"`
	Exited   bool                   `protobuf:"varint,4,opt,name=exited,proto3" json:"exited,omitempty"`
	ExitCode int32                  `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// sandbox.SessionExitReason: 0 exited, 1 signaled, 2 terminated.
	Reason        uint32 `protobuf:"varint,6,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadOk) Reset() {
	*x = ReadOk{}
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadOk) ProtoMessage() {}

func (x *ReadOk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadOk.ProtoReflect.Descriptor instead.
func (*ReadOk) Descriptor() ([]byte, []int) {
	return file_internal_capabilities_execd_execd_proto_rawDescGZIP(), []int{16}
}

func (x *ReadOk) GetChunks() []*Chunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *ReadOk) GetNextSeq() int64 {
	if x != nil {
		return x.NextSeq
	}
	return 0
}

func (x *ReadOk) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

func (x *ReadOk) GetExited() bool {
	if x != nil {
		return x.Exited
	}
	return false
}

func (x *ReadOk) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ReadOk) GetReason() uint32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

type Write struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessId     string                 `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	Chunk         []byte                 `protobuf:"bytes,2,opt,name=chunk,proto3" json:"chunk,omitempty"`
	WriteId       string                 `protobuf:"bytes,3,opt,name=write_id,json=writeId,proto3" json:"write_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Write) Reset() {
	*x = Write{}
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Write) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Write) ProtoMessage() {}

func (x *Write) ProtoReflect() protoreflect.Message {
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Write.ProtoReflect.Descriptor instead.
func (*Write) Descriptor() ([]byte, []int) {
	return file_internal_capabilities_execd_execd_proto_rawDescGZIP(), []int{17}
}

func (x *Write) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *Write) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *Write) GetWriteId() string {
	if x != nil {
		return x.WriteId
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_internal_capabilities_execd_execd_proto_rawDescGZIP(), []int{18}
}

func (x *Ack) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CloseInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessId     string                 `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseInput) Reset() {
	*x = CloseInput{}
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseInput) ProtoMessage() {}

func (x *CloseInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseInput.ProtoReflect.Descriptor instead.
func (*CloseInput) Descriptor() ([]byte, []int) {
	return file_internal_capabilities_execd_execd_proto_rawDescGZIP(), []int{19}
}

func (x *CloseInput) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

type Signal struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ProcessId string                 `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	// sandbox.SessionSignal: 0 interrupt.
	Signal        uint32 `protobuf:"varint,2,opt,name=signal,proto3" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signal) Reset() {
	*x = Signal{}
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signal) ProtoMessage() {}

func (x *Signal) ProtoReflect() protoreflect.Message {
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signal.ProtoReflect.Descriptor instead.
func (*Signal) Descriptor() ([]byte, []int) {
	return file_internal_capabilities_execd_execd_proto_rawDescGZIP(), []int{20}
}

func (x *Signal) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *Signal) GetSignal() uint32 {
	if x != nil {
		return x.Signal
	}
	return 0
}

type Resize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessId     string                 `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	Rows          int32                  `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          int32                  `protobuf:"varint,3,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resize) Reset() {
	*x = Resize{}
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resize) ProtoMessage() {}

func (x *Resize) ProtoReflect() protoreflect.Message {
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resize.ProtoReflect.Descriptor instead.
func (*Resize) Descriptor() ([]byte, []int) {
	return file_internal_capabilities_execd_execd_proto_rawDescGZIP(), []int{21}
}

func (x *Resize) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *Resize) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *Resize) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

type Terminate struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ProcessId string                 `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	// Force skips the SIGTERM grace window (session Close semantics).
	Force         bool `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Terminate) Reset() {
	*x = Terminate{}
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Terminate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Terminate) ProtoMessage() {}

func (x *Terminate) ProtoReflect() protoreflect.Message {
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Terminate.ProtoReflect.Descriptor instead.
func (*Terminate) Descriptor() ([]byte, []int) {
	return file_internal_capabilities_execd_execd_proto_rawDescGZIP(), []int{22}
}

func (x *Terminate) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *Terminate) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type TerminateOk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Running       bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateOk) Reset() {
	*x = TerminateOk{}
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateOk) ProtoMessage() {}

func (x *TerminateOk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateOk.ProtoReflect.Descriptor instead.
func (*TerminateOk) Descriptor() ([]byte, []int) {
	return file_internal_capabilities_execd_execd_proto_rawDescGZIP(), []int{23}
}

func (x *TerminateOk) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

type Release struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessId     string                 `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Release) Reset() {
	*x = Release{}
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Release) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Release) ProtoMessage() {}

func (x *Release) ProtoReflect() protoreflect.Message {
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Release.ProtoReflect.Descriptor instead.
func (*Release) Descriptor() ([]byte, []int) {
	return file_internal_capabilities_execd_execd_proto_rawDescGZIP(), []int{24}
}

func (x *Release) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

type ReleaseOk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Released      bool                   `protobuf:"varint,1,opt,name=released,proto3" json:"released,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseOk) Reset() {
	*x = ReleaseOk{}
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseOk) ProtoMessage() {}

func (x *ReleaseOk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseOk.ProtoReflect.Descriptor instead.
func (*ReleaseOk) Descriptor() ([]byte, []int) {
	return file_internal_capabilities_execd_execd_proto_rawDescGZIP(), []int{25}
}

func (x *ReleaseOk) GetReleased() bool {
	if x != nil {
		return x.Released
	}
	return false
}

type Wait struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessId     string                 `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wait) Reset() {
	*x = Wait{}
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wait) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wait) ProtoMessage() {}

func (x *Wait) ProtoReflect() protoreflect.Message {
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wait.ProtoReflect.Descriptor instead.
func (*Wait) Descriptor() ([]byte, []int) {
	return file_internal_capabilities_execd_execd_proto_rawDescGZIP(), []int{26}
}

func (x *Wait) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

type WaitOk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Reason        uint32                 `protobuf:"varint,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitOk) Reset() {
	*x = WaitOk{}
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitOk) ProtoMessage() {}

func (x *WaitOk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitOk.ProtoReflect.Descriptor instead.
func (*WaitOk) Descriptor() ([]byte, []int) {
	return file_internal_capabilities_execd_execd_proto_rawDescGZIP(), []int{27}
}

func (x *WaitOk) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *WaitOk) GetReason() uint32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_internal_capabilities_execd_execd_proto_rawDescGZIP(), []int{28}
}

type PingOk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UptimeMs      int64                  `protobuf:"varint,1,opt,name=uptime_ms,json=uptimeMs,proto3" json:"uptime_ms,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingOk) Reset() {
	*x = PingOk{}
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingOk) ProtoMessage() {}

func (x *PingOk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingOk.ProtoReflect.Descriptor instead.
func (*PingOk) Descriptor() ([]byte, []int) {
	return file_internal_capabilities_execd_execd_proto_rawDescGZIP(), []int{29}
}

func (x *PingOk) GetUptimeMs() int64 {
	if x != nil {
		return x.UptimeMs
	}
	return 0
}

func (x *PingOk) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Diagnostics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Diagnostics) Reset() {
	*x = Diagnostics{}
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diagnostics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagnostics) ProtoMessage() {}

func (x *Diagnostics) ProtoReflect() protoreflect.Message {
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagnostics.ProtoReflect.Descriptor instead.
func (*Diagnostics) Descriptor() ([]byte, []int) {
	return file_internal_capabilities_execd_execd_proto_rawDescGZIP(), []int{30}
}

type DiagnosticsOk struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Version              string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	ProtocolVersion      uint32                 `protobuf:"varint,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	UptimeMs             int64                  `protobuf:"varint,3,opt,name=uptime_ms,json=uptimeMs,proto3" json:"uptime_ms,omitempty"`
	Bound                bool                   `protobuf:"varint,4,opt,name=bound,proto3" json:"bound,omitempty"`
	Workdir              string                 `protobuf:"bytes,5,opt,name=workdir,proto3" json:"workdir,omitempty"`
	Processes            int32                  `protobuf:"varint,6,opt,name=processes,proto3" json:"processes,omitempty"`
	Goroutines           int32                  `protobuf:"varint,7,opt,name=goroutines,proto3" json:"goroutines,omitempty"`
	QueuedFrames         int32                  `protobuf:"varint,8,opt,name=queued_frames,json=queuedFrames,proto3" json:"queued_frames,omitempty"`
	QueuedBytes          int64                  `protobuf:"varint,9,opt,name=queued_bytes,json=queuedBytes,proto3" json:"queued_bytes,omitempty"`
	DroppedNotifications int64                  `protobuf:"varint,10,opt,name=dropped_notifications,json=droppedNotifications,proto3" json:"dropped_notifications,omitempty"`
	ReleasedProcesses    int64                  `protobuf:"varint,11,opt,name=released_processes,json=releasedProcesses,proto3" json:"released_processes,omitempty"`
	ReapedProcesses      int64                  `protobuf:"varint,12,opt,name=reaped_processes,json=reapedProcesses,proto3" json:"reaped_processes,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DiagnosticsOk) Reset() {
	*x = DiagnosticsOk{}
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnosticsOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosticsOk) ProtoMessage() {}

func (x *DiagnosticsOk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosticsOk.ProtoReflect.Descriptor instead.
func (*DiagnosticsOk) Descriptor() ([]byte, []int) {
	return file_internal_capabilities_execd_execd_proto_rawDescGZIP(), []int{31}
}

func (x *DiagnosticsOk) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DiagnosticsOk) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *DiagnosticsOk) GetUptimeMs() int64 {
	if x != nil {
		return x.UptimeMs
	}
	return 0
}

func (x *DiagnosticsOk) GetBound() bool {
	if x != nil {
		return x.Bound
	}
	return false
}

func (x *DiagnosticsOk) GetWorkdir() string {
	if x != nil {
		return x.Workdir
	}
	return ""
}

func (x *DiagnosticsOk) GetProcesses() int32 {
	if x != nil {
		return x.Processes
	}
	return 0
}

func (x *DiagnosticsOk) GetGoroutines() int32 {
	if x != nil {
		return x.Goroutines
	}
	return 0
}

func (x *DiagnosticsOk) GetQueuedFrames() int32 {
	if x != nil {
		return x.QueuedFrames
	}
	return 0
}

func (x *DiagnosticsOk) GetQueuedBytes() int64 {
	if x != nil {
		return x.QueuedBytes
	}
	return 0
}

func (x *DiagnosticsOk) GetDroppedNotifications() int64 {
	if x != nil {
		return x.DroppedNotifications
	}
	return 0
}

func (x *DiagnosticsOk) GetReleasedProcesses() int64 {
	if x != nil {
		return x.ReleasedProcesses
	}
	return 0
}

func (x *DiagnosticsOk) GetReapedProcesses() int64 {
	if x != nil {
		return x.ReapedProcesses
	}
	return 0
}

type Cancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cancel) Reset() {
	*x = Cancel{}
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cancel) ProtoMessage() {}

func (x *Cancel) ProtoReflect() protoreflect.Message {
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cancel.ProtoReflect.Descriptor instead.
func (*Cancel) Descriptor() ([]byte, []int) {
	return file_internal_capabilities_execd_execd_proto_rawDescGZIP(), []int{32}
}

func (x *Cancel) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type Output struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessId     string                 `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	Seq           int64                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Stream        uint32                 `protobuf:"varint,3,opt,name=stream,proto3" json:"stream,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Output) Reset() {
	*x = Output{}
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_internal_capabilities_execd_execd_proto_rawDescGZIP(), []int{33}
}

func (x *Output) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *Output) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Output) GetStream() uint32 {
	if x != nil {
		return x.Stream
	}
	return 0
}

func (x *Output) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Exited struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessId     string                 `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	Seq           int64                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Reason        uint32                 `protobuf:"varint,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exited) Reset() {
	*x = Exited{}
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exited) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exited) ProtoMessage() {}

func (x *Exited) ProtoReflect() protoreflect.Message {
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exited.ProtoReflect.Descriptor instead.
func (*Exited) Descriptor() ([]byte, []int) {
	return file_internal_capabilities_execd_execd_proto_rawDescGZIP(), []int{34}
}

func (x *Exited) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *Exited) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Exited) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *Exited) GetReason() uint32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

type Closed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessId     string                 `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	Seq           int64                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Closed) Reset() {
	*x = Closed{}
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Closed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Closed) ProtoMessage() {}

func (x *Closed) ProtoReflect() protoreflect.Message {
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Closed.ProtoReflect.Descriptor instead.
func (*Closed) Descriptor() ([]byte, []int) {
	return file_internal_capabilities_execd_execd_proto_rawDescGZIP(), []int{35}
}

func (x *Closed) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *Closed) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type Lag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessId     string                 `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	Seq           int64                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lag) Reset() {
	*x = Lag{}
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lag) ProtoMessage() {}

func (x *Lag) ProtoReflect() protoreflect.Message {
	mi := &file_internal_capabilities_execd_execd_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lag.ProtoReflect.Descriptor instead.
func (*Lag) Descriptor() ([]byte, []int) {
	return file_internal_capabilities_execd_execd_proto_rawDescGZIP(), []int{36}
}

func (x *Lag) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *Lag) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

var File_internal_capabilities_execd_execd_proto protoreflect.FileDescriptor

const file_internal_capabilities_execd_execd_proto_rawDesc = "" +
	"\n" +
	"'internal/capabilities/execd/execd.proto\x12\x12opencraft.execd.v1\"\xfd\x01\n" +
	"\x05Frame\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1f\n" +
	"\vdeadline_ms\x18\x02 \x01(\x03R\n" +
	"deadlineMs\x127\n" +
	"\arequest\x18\x03 \x01(\v2\x1b.opencraft.execd.v1.RequestH\x00R\arequest\x12:\n" +
	"\bresponse\x18\x04 \x01(\v2\x1c.opencraft.execd.v1.ResponseH\x00R\bresponse\x12F\n" +
	"\fnotification\x18\x05 \x01(\v2 .opencraft.execd.v1.NotificationH\x00R\fnotificationB\x06\n" +
	"\x04body\"\x8e\x06\n" +
	"\aRequest\x121\n" +
	"\x05hello\x18\x01 \x01(\v2\x19.opencraft.execd.v1.HelloH\x00R\x05hello\x12.\n" +
	"\x04bind\x18\x02 \x01(\v2\x18.opencraft.execd.v1.BindH\x00R\x04bind\x124\n" +
	"\x06unbind\x18\x03 \x01(\v2\x1a.opencraft.execd.v1.UnbindH\x00R\x06unbind\x121\n" +
	"\x05start\x18\x04 \x01(\v2\x19.opencraft.execd.v1.StartH\x00R\x05start\x12.\n" +
	"\x04read\x18\x05 \x01(\v2\x18.opencraft.execd.v1.ReadH\x00R\x04read\x121\n" +
	"\x05write\x18\x06 \x01(\v2\x19.opencraft.execd.v1.WriteH\x00R\x05write\x12A\n" +
	"\vclose_input\x18\a \x01(\v2\x1e.opencraft.execd.v1.CloseInputH\x00R\n" +
	"closeInput\x124\n" +
	"\x06signal\x18\b \x01(\v2\x1a.opencraft.execd.v1.SignalH\x00R\x06signal\x124\n" +
	"\x06resize\x18\t \x01(\v2\x1a.opencraft.execd.v1.ResizeH\x00R\x06resize\x12=\n" +
	"\tterminate\x18\n" +
	" \x01(\v2\x1d.opencraft.execd.v1.TerminateH\x00R\tterminate\x127\n" +
	"\arelease\x18\v \x01(\v2\x1b.opencraft.execd.v1.ReleaseH\x00R\arelease\x12.\n" +
	"\x04wait\x18\f \x01(\v2\x18.opencraft.execd.v1.WaitH\x00R\x04wait\x12.\n" +
	"\x04ping\x18\r \x01(\v2\x18.opencraft.execd.v1.PingH\x00R\x04ping\x12C\n" +
	"\vdiagnostics\x18\x0e \x01(\v2\x1f.opencraft.execd.v1.DiagnosticsH\x00R\vdiagnosticsB\b\n" +
	"\x06method\"\x94\x05\n" +
	"\bResponse\x121\n" +
	"\x05error\x18\x01 \x01(\v2\x19.opencraft.execd.v1.ErrorH\x00R\x05error\x128\n" +
	"\bhello_ok\x18\x02 \x01(\v2\x1b.opencraft.execd.v1.HelloOkH\x00R\ahelloOk\x125\n" +
	"\abind_ok\x18\x03 \x01(\v2\x1a.opencraft.execd.v1.BindOkH\x00R\x06bindOk\x12+\n" +
	"\x03ack\x18\x04 \x01(\v2\x17.opencraft.execd.v1.AckH\x00R\x03ack\x128\n" +
	"\bstart_ok\x18\x05 \x01(\v2\x1b.opencraft.execd.v1.StartOkH\x00R\astartOk\x125\n" +
	"\aread_ok\x18\x06 \x01(\v2\x1a.opencraft.execd.v1.ReadOkH\x00R\x06readOk\x12D\n" +
	"\fterminate_ok\x18\a \x01(\v2\x1f.opencraft.execd.v1.TerminateOkH\x00R\vterminateOk\x12>\n" +
	"\n" +
	"release_ok\x18\b \x01(\v2\x1d.opencraft.execd.v1.ReleaseOkH\x00R\treleaseOk\x125\n" +
	"\await_ok\x18\t \x01(\v2\x1a.opencraft.execd.v1.WaitOkH\x00R\x06waitOk\x125\n" +
	"\aping_ok\x18\n" +
	" \x01(\v2\x1a.opencraft.execd.v1.PingOkH\x00R\x06pingOk\x12J\n" +
	"\x0ediagnostics_ok\x18\v \x01(\v2!.opencraft.execd.v1.DiagnosticsOkH\x00R\rdiagnosticsOkB\x06\n" +
	"\x04body\"\x9b\x02\n" +
	"\fNotification\x124\n" +
	"\x06cancel\x18\x01 \x01(\v2\x1a.opencraft.execd.v1.CancelH\x00R\x06cancel\x124\n" +
	"\x06output\x18\x02 \x01(\v2\x1a.opencraft.execd.v1.OutputH\x00R\x06output\x124\n" +
	"\x06exited\x18\x03 \x01(\v2\x1a.opencraft.execd.v1.ExitedH\x00R\x06exited\x124\n" +
	"\x06closed\x18\x04 \x01(\v2\x1a.opencraft.execd.v1.ClosedH\x00R\x06closed\x12+\n" +
	"\x03lag\x18\x05 \x01(\v2\x17.opencraft.execd.v1.LagH\x00R\x03lagB\x06\n" +
	"\x04body\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"`\n" +
	"\x05Hello\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x14\n" +
	"\x05build\x18\x02 \x01(\tR\x05build\x12\x16\n" +
	"\x06client\x18\x03 \x01(\tR\x06client\"\x8d\x01\n" +
	"\aHelloOk\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x14\n" +
	"\x05build\x18\x02 \x01(\tR\x05build\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\"\x86\x02\n" +
	"\rSandboxPolicy\x12%\n" +
	"\x0ewritable_paths\x18\x01 \x03(\tR\rwritablePaths\x12\x1b\n" +
	"\tenv_allow\x18\x02 \x03(\tR\benvAllow\x12O\n" +
	"\n" +
	"env_inject\x18\x03 \x03(\v20.opencraft.execd.v1.SandboxPolicy.EnvInjectEntryR\tenvInject\x12\"\n" +
	"\renv_allow_set\x18\x04 \x01(\bR\venvAllowSet\x1a<\n" +
	"\x0eEnvInjectEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"[\n" +
	"\x04Bind\x12\x18\n" +
	"\aworkdir\x18\x01 \x01(\tR\aworkdir\x129\n" +
	"\x06policy\x18\x02 \x01(\v2!.opencraft.execd.v1.SandboxPolicyR\x06policy\"\b\n" +
	"\x06BindOk\"\b\n" +
	"\x06Unbind\"\xfc\x03\n" +
	"\vExecOptions\x12\x19\n" +
	"\bwork_dir\x18\x01 \x01(\tR\aworkDir\x12\x14\n" +
	"\x05stdin\x18\x02 \x01(\fR\x05stdin\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x03R\ttimeoutMs\x12\x1b\n" +
	"\tenv_allow\x18\x04 \x03(\tR\benvAllow\x12M\n" +
	"\n" +
	"env_inject\x18\x05 \x03(\v2..opencraft.execd.v1.ExecOptions.EnvInjectEntryR\tenvInject\x12\"\n" +
	"\renv_allow_set\x18\x06 \x01(\bR\venvAllowSet\x12\x14\n" +
	"\x05write\x18\a \x01(\rR\x05write\x12!\n" +
	"\fmemory_bytes\x18\b \x01(\x03R\vmemoryBytes\x12%\n" +
	"\x0ecpu_millicores\x18\t \x01(\x03R\rcpuMillicores\x12\x1d\n" +
	"\n" +
	"disk_bytes\x18\n" +
	" \x01(\x03R\tdiskBytes\x12(\n" +
	"\x10max_output_bytes\x18\v \x01(\x03R\x0emaxOutputBytes\x12&\n" +
	"\x0fnet_policy_json\x18\f \x01(\fR\rnetPolicyJson\x1a<\n" +
	"\x0eEnvInjectEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xee\x02\n" +
	"\x05Start\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\x12\x12\n" +
	"\x04argv\x18\x02 \x03(\tR\x04argv\x12\x10\n" +
	"\x03cwd\x18\x03 \x01(\tR\x03cwd\x124\n" +
	"\x03env\x18\x04 \x03(\v2\".opencraft.execd.v1.Start.EnvEntryR\x03env\x12\x10\n" +
	"\x03tty\x18\x05 \x01(\bR\x03tty\x12\x12\n" +
	"\x04rows\x18\x06 \x01(\x05R\x04rows\x12\x12\n" +
	"\x04cols\x18\a \x01(\x05R\x04cols\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\b \x01(\x03R\ttimeoutMs\x12\x1e\n" +
	"\n" +
	"unconfined\x18\t \x01(\bR\n" +
	"unconfined\x129\n" +
	"\asandbox\x18\n" +
	" \x01(\v2\x1f.opencraft.execd.v1.ExecOptionsR\asandbox\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1b\n" +
	"\aStartOk\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\"x\n" +
	"\x04Read\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\x12\x1b\n" +
	"\tafter_seq\x18\x02 \x01(\x03R\bafterSeq\x12\x1b\n" +
	"\tmax_bytes\x18\x03 \x01(\x05R\bmaxBytes\x12\x17\n" +
	"\await_ms\x18\x04 \x01(\x03R\x06waitMs\"E\n" +
	"\x05Chunk\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\x12\x16\n" +
	"\x06stream\x18\x02 \x01(\rR\x06stream\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\xb5\x01\n" +
	"\x06ReadOk\x121\n" +
	"\x06chunks\x18\x01 \x03(\v2\x19.opencraft.execd.v1.ChunkR\x06chunks\x12\x19\n" +
	"\bnext_seq\x18\x02 \x01(\x03R\anextSeq\x12\x10\n" +
	"\x03eof\x18\x03 \x01(\bR\x03eof\x12\x16\n" +
	"\x06exited\x18\x04 \x01(\bR\x06exited\x12\x1b\n" +
	"\texit_code\x18\x05 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\rR\x06reason\"W\n" +
	"\x05Write\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\x12\x14\n" +
	"\x05chunk\x18\x02 \x01(\fR\x05chunk\x12\x19\n" +
	"\bwrite_id\x18\x03 \x01(\tR\awriteId\"\x1d\n" +
	"\x03Ack\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"+\n" +
	"\n" +
	"CloseInput\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\"?\n" +
	"\x06Signal\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\rR\x06signal\"O\n" +
	"\x06Resize\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\x05R\x04rows\x12\x12\n" +
	"\x04cols\x18\x03 \x01(\x05R\x04cols\"@\n" +
	"\tTerminate\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"'\n" +
	"\vTerminateOk\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\"(\n" +
	"\aRelease\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\"'\n" +
	"\tReleaseOk\x12\x1a\n" +
	"\breleased\x18\x01 \x01(\bR\breleased\"%\n" +
	"\x04Wait\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\"=\n" +
	"\x06WaitOk\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\rR\x06reason\"\x06\n" +
	"\x04Ping\"?\n" +
	"\x06PingOk\x12\x1b\n" +
	"\tuptime_ms\x18\x01 \x01(\x03R\buptimeMs\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\r\n" +
	"\vDiagnostics\"\xb6\x03\n" +
	"\rDiagnosticsOk\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\rR\x0fprotocolVersion\x12\x1b\n" +
	"\tuptime_ms\x18\x03 \x01(\x03R\buptimeMs\x12\x14\n" +
	"\x05bound\x18\x04 \x01(\bR\x05bound\x12\x18\n" +
	"\aworkdir\x18\x05 \x01(\tR\aworkdir\x12\x1c\n" +
	"\tprocesses\x18\x06 \x01(\x05R\tprocesses\x12\x1e\n" +
	"\n" +
	"goroutines\x18\a \x01(\x05R\n" +
	"goroutines\x12#\n" +
	"\rqueued_frames\x18\b \x01(\x05R\fqueuedFrames\x12!\n" +
	"\fqueued_bytes\x18\t \x01(\x03R\vqueuedBytes\x123\n" +
	"\x15dropped_notifications\x18\n" +
	" \x01(\x03R\x14droppedNotifications\x12-\n" +
	"\x12released_processes\x18\v \x01(\x03R\x11releasedProcesses\x12)\n" +
	"\x10reaped_processes\x18\f \x01(\x03R\x0freapedProcesses\"'\n" +
	"\x06Cancel\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\"e\n" +
	"\x06Output\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x03R\x03seq\x12\x16\n" +
	"\x06stream\x18\x03 \x01(\rR\x06stream\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"n\n" +
	"\x06Exited\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x03R\x03seq\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\rR\x06reason\"9\n" +
	"\x06Closed\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x03R\x03seq\"6\n" +
	"\x03Lag\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x03R\x03seqB:Z8github.com/GizClaw/opencraft/internal/capabilities/execdb\x06proto3"

var (
	file_internal_capabilities_execd_execd_proto_rawDescOnce sync.Once
	file_internal_capabilities_execd_execd_proto_rawDescData []byte
)

func file_internal_capabilities_execd_execd_proto_rawDescGZIP() []byte {
	file_internal_capabilities_execd_execd_proto_rawDescOnce.Do(func() {
		file_internal_capabilities_execd_execd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_capabilities_execd_execd_proto_rawDesc), len(file_internal_capabilities_execd_execd_proto_rawDesc)))
	})
	return file_internal_capabilities_execd_execd_proto_rawDescData
}

var file_internal_capabilities_execd_execd_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_internal_capabilities_execd_execd_proto_goTypes = []any{
	(*Frame)(nil),         // 0: opencraft.execd.v1.Frame
	(*Request)(nil),       // 1: opencraft.execd.v1.Request
	(*Response)(nil),      // 2: opencraft.execd.v1.Response
	(*Notification)(nil),  // 3: opencraft.execd.v1.Notification
	(*Error)(nil),         // 4: opencraft.execd.v1.Error
	(*Hello)(nil),         // 5: opencraft.execd.v1.Hello
	(*HelloOk)(nil),       // 6: opencraft.execd.v1.HelloOk
	(*SandboxPolicy)(nil), // 7: opencraft.execd.v1.SandboxPolicy
	(*Bind)(nil),          // 8: opencraft.execd.v1.Bind
	(*BindOk)(nil),        // 9: opencraft.execd.v1.BindOk
	(*Unbind)(nil),        // 10: opencraft.execd.v1.Unbind
	(*ExecOptions)(nil),   // 11: opencraft.execd.v1.ExecOptions
	(*Start)(nil),         // 12: opencraft.execd.v1.Start
	(*StartOk)(nil),       // 13: opencraft.execd.v1.StartOk
	(*Read)(nil),          // 14: opencraft.execd.v1.Read
	(*Chunk)(nil),         // 15: opencraft.execd.v1.Chunk
	(*ReadOk)(nil),        // 16: opencraft.execd.v1.ReadOk
	(*Write)(nil),         // 17: opencraft.execd.v1.Write
	(*Ack)(nil),           // 18: opencraft.execd.v1.Ack
	(*CloseInput)(nil),    // 19: opencraft.execd.v1.CloseInput
	(*Signal)(nil),        // 20: opencraft.execd.v1.Signal
	(*Resize)(nil),        // 21: opencraft.execd.v1.Resize
	(*Terminate)(nil),     // 22: opencraft.execd.v1.Terminate
	(*TerminateOk)(nil),   // 23: opencraft.execd.v1.TerminateOk
	(*Release)(nil),       // 24: opencraft.execd.v1.Release
	(*ReleaseOk)(nil),     // 25: opencraft.execd.v1.ReleaseOk
	(*Wait)(nil),          // 26: opencraft.execd.v1.Wait
	(*WaitOk)(nil),        // 27: opencraft.execd.v1.WaitOk
	(*Ping)(nil),          // 28: opencraft.execd.v1.Ping
	(*PingOk)(nil),        // 29: opencraft.execd.v1.PingOk
	(*Diagnostics)(nil),   // 30: opencraft.execd.v1.Diagnostics
	(*DiagnosticsOk)(nil), // 31: opencraft.execd.v1.DiagnosticsOk
	(*Cancel)(nil),        // 32: opencraft.execd.v1.Cancel
	(*Output)(nil),        // 33: opencraft.execd.v1.Output
	(*Exited)(nil),        // 34: opencraft.execd.v1.Exited
	(*Closed)(nil),        // 35: opencraft.execd.v1.Closed
	(*Lag)(nil),           // 36: opencraft.execd.v1.Lag
	nil,                   // 37: opencraft.execd.v1.SandboxPolicy.EnvInjectEntry
	nil,                   // 38: opencraft.execd.v1.ExecOptions.EnvInjectEntry
	nil,                   // 39: opencraft.execd.v1.Start.EnvEntry
}
var file_internal_capabilities_execd_execd_proto_depIdxs = []int32{
	1,  // 0: opencraft.execd.v1.Frame.request:type_name -> opencraft.execd.v1.Request
	2,  // 1: opencraft.execd.v1.Frame.response:type_name -> opencraft.execd.v1.Response
	3,  // 2: opencraft.execd.v1.Frame.notification:type_name -> opencraft.execd.v1.Notification
	5,  // 3: opencraft.execd.v1.Request.hello:type_name -> opencraft.execd.v1.Hello
	8,  // 4: opencraft.execd.v1.Request.bind:type_name -> opencraft.execd.v1.Bind
	10, // 5: opencraft.execd.v1.Request.unbind:type_name -> opencraft.execd.v1.Unbind
	12, // 6: opencraft.execd.v1.Request.start:type_name -> opencraft.execd.v1.Start
	14, // 7: opencraft.execd.v1.Request.read:type_name -> opencraft.execd.v1.Read
	17, // 8: opencraft.execd.v1.Request.write:type_name -> opencraft.execd.v1.Write
	19, // 9: opencraft.execd.v1.Request.close_input:type_name -> opencraft.execd.v1.CloseInput
	20, // 10: opencraft.execd.v1.Request.signal:type_name -> opencraft.execd.v1.Signal
	21, // 11: opencraft.execd.v1.Request.resize:type_name -> opencraft.execd.v1.Resize
	22, // 12: opencraft.execd.v1.Request.terminate:type_name -> opencraft.execd.v1.Terminate
	24, // 13: opencraft.execd.v1.Request.release:type_name -> opencraft.execd.v1.Release
	26, // 14: opencraft.execd.v1.Request.wait:type_name -> opencraft.execd.v1.Wait
	28, // 15: opencraft.execd.v1.Request.ping:type_name -> opencraft.execd.v1.Ping
	30, // 16: opencraft.execd.v1.Request.diagnostics:type_name -> opencraft.execd.v1.Diagnostics
	4,  // 17: opencraft.execd.v1.Response.error:type_name -> opencraft.execd.v1.Error
	6,  // 18: opencraft.execd.v1.Response.hello_ok:type_name -> opencraft.execd.v1.HelloOk
	9,  // 19: opencraft.execd.v1.Response.bind_ok:type_name -> opencraft.execd.v1.BindOk
	18, // 20: opencraft.execd.v1.Response.ack:type_name -> opencraft.execd.v1.Ack
	13, // 21: opencraft.execd.v1.Response.start_ok:type_name -> opencraft.execd.v1.StartOk
	16, // 22: opencraft.execd.v1.Response.read_ok:type_name -> opencraft.execd.v1.ReadOk
	23, // 23: opencraft.execd.v1.Response.terminate_ok:type_name -> opencraft.execd.v1.TerminateOk
	25, // 24: opencraft.execd.v1.Response.release_ok:type_name -> opencraft.execd.v1.ReleaseOk
	27, // 25: opencraft.execd.v1.Response.wait_ok:type_name -> opencraft.execd.v1.WaitOk
	29, // 26: opencraft.execd.v1.Response.ping_ok:type_name -> opencraft.execd.v1.PingOk
	31, // 27: opencraft.execd.v1.Response.diagnostics_ok:type_name -> opencraft.execd.v1.DiagnosticsOk
	32, // 28: opencraft.execd.v1.Notification.cancel:type_name -> opencraft.execd.v1.Cancel
	33, // 29: opencraft.execd.v1.Notification.output:type_name -> opencraft.execd.v1.Output
	34, // 30: opencraft.execd.v1.Notification.exited:type_name -> opencraft.execd.v1.Exited
	35, // 31: opencraft.execd.v1.Notification.closed:type_name -> opencraft.execd.v1.Closed
	36, // 32: opencraft.execd.v1.Notification.lag:type_name -> opencraft.execd.v1.Lag
	37, // 33: opencraft.execd.v1.SandboxPolicy.env_inject:type_name -> opencraft.execd.v1.SandboxPolicy.EnvInjectEntry
	7,  // 34: opencraft.execd.v1.Bind.policy:type_name -> opencraft.execd.v1.SandboxPolicy
	38, // 35: opencraft.execd.v1.ExecOptions.env_inject:type_name -> opencraft.execd.v1.ExecOptions.EnvInjectEntry
	39, // 36: opencraft.execd.v1.Start.env:type_name -> opencraft.execd.v1.Start.EnvEntry
	11, // 37: opencraft.execd.v1.Start.sandbox:type_name -> opencraft.execd.v1.ExecOptions
	15, // 38: opencraft.execd.v1.ReadOk.chunks:type_name -> opencraft.execd.v1.Chunk
	39, // [39:39] is the sub-list for method output_type
	39, // [39:39] is the sub-list for method input_type
	39, // [39:39] is the sub-list for extension type_name
	39, // [39:39] is the sub-list for extension extendee
	0,  // [0:39] is the sub-list for field type_name
}

func init() { file_internal_capabilities_execd_execd_proto_init() }
func file_internal_capabilities_execd_execd_proto_init() {
	if File_internal_capabilities_execd_execd_proto != nil {
		return
	}
	file_internal_capabilities_execd_execd_proto_msgTypes[0].OneofWrappers = []any{
		(*Frame_Request)(nil),
		(*Frame_Response)(nil),
		(*Frame_Notification)(nil),
	}
	file_internal_capabilities_execd_execd_proto_msgTypes[1].OneofWrappers = []any{
		(*Request_Hello)(nil),
		(*Request_Bind)(nil),
		(*Request_Unbind)(nil),
		(*Request_Start)(nil),
		(*Request_Read)(nil),
		(*Request_Write)(nil),
		(*Request_CloseInput)(nil),
		(*Request_Signal)(nil),
		(*Request_Resize)(nil),
		(*Request_Terminate)(nil),
		(*Request_Release)(nil),
		(*Request_Wait)(nil),
		(*Request_Ping)(nil),
		(*Request_Diagnostics)(nil),
	}
	file_internal_capabilities_execd_execd_proto_msgTypes[2].OneofWrappers = []any{
		(*Response_Error)(nil),
		(*Response_HelloOk)(nil),
		(*Response_BindOk)(nil),
		(*Response_Ack)(nil),
		(*Response_StartOk)(nil),
		(*Response_ReadOk)(nil),
		(*Response_TerminateOk)(nil),
		(*Response_ReleaseOk)(nil),
		(*Response_WaitOk)(nil),
		(*Response_PingOk)(nil),
		(*Response_DiagnosticsOk)(nil),
	}
	file_internal_capabilities_execd_execd_proto_msgTypes[3].OneofWrappers = []any{
		(*Notification_Cancel)(nil),
		(*Notification_Output)(nil),
		(*Notification_Exited)(nil),
		(*Notification_Closed)(nil),
		(*Notification_Lag)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_capabilities_execd_execd_proto_rawDesc), len(file_internal_capabilities_execd_execd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_capabilities_execd_execd_proto_goTypes,
		DependencyIndexes: file_internal_capabilities_execd_execd_proto_depIdxs,
		MessageInfos:      file_internal_capabilities_execd_execd_proto_msgTypes,
	}.Build()
	File_internal_capabilities_execd_execd_proto = out.File
	file_internal_capabilities_execd_execd_proto_goTypes = nil
	file_internal_capabilities_execd_execd_proto_depIdxs = nil
}
