// Package config owns opencraft's embedded deploy assets: the internal
// base opencraft.yaml document, the graph definition, and prompt
// templates. The user configuration layer (~/.opencraft/config/
// opencraft.yaml) is generated by the first-run setup wizard, not
// embedded here.
package config

import "embed"

// Default deploy assets. The base opencraft.yaml stays embedded as
// internal wiring; the user layer is generated by the first-run setup
// wizard into ~/.opencraft/config/opencraft.yaml (single editable
// document). The graph definition and its node scripts/prompt are
// embedded too — they are only read from disk when a config layer
// overrides the graph reference with a {file: ...} source.
//
//go:embed assets
var assets embed.FS

// FS returns the embedded deploy asset filesystem (for embed sources
// referenced from opencraft.yaml, e.g. the graph definition).
func FS() embed.FS { return assets }

// EmbeddedOpenCraft returns the internal deploy document.
func EmbeddedOpenCraft() ([]byte, error) {
	return assets.ReadFile("assets/opencraft.yaml")
}
